name: visp
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake
  - clang
  - ninja
  - llvm-openmp
  - openmp
  - pthreads-win32
  - libopencv
  - eigen
  - libjpeg-turbo
  - libpng
  - mkl-devel
  - pybind11
  - libiconv <=1.17
